# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ java/release/3.3 ]
  pull_request:
    branches: [ java/release/3.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - id : tests
        name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Send a Slack notification saying if tests are passing/failing for a given Java version
        shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          conclusion=${{ steps.tests.conclusion }}
          if [[ "$conclusion" == "success" ]]; then
            message="✅ Java SDK Test succeeded for Java ${{ matrix.java }}"
          else
            message="❌ Java SDK Test failed for Java ${{ matrix.java }}"
          fi
          curl -X POST --data-urlencode "payload={\"text\": \"$message\", \"link_names\": 1}" $SLACK_WEBHOOK_URL
